<?= $this->extend('layouts/public') ?><?= $this->section('content') ?>
<section class="page-header"><div class="container narrow"><p class="eyebrow">Draft application</p><h1>Complete your admission application</h1><p class="lead">Save biodata, O'Level results, and private documents before final preview and submission.</p></div></section>
<section class="section"><div class="container narrow content-stack">
<?php if (session('message')): ?><p class="notice"><?= esc(session('message')) ?></p><?php endif ?><?php if (session('errors')): ?><ul><?php foreach(session('errors') as $error): ?><li><?= esc($error) ?></li><?php endforeach ?></ul><?php endif ?>
<?php $b=$application['biodata'] ?? []; ?>
<form method="post" action="<?= site_url('applicant/applications/'.$application['public_token'].'/biodata') ?>" id="applicant-biodata-form" data-autosave-endpoint="<?= esc(site_url('applicant/applications/'.$application['public_token'].'/biodata')) ?>" data-csrf-header="<?= esc(csrf_header()) ?>" data-csrf-token="<?= esc(csrf_hash()) ?>"><?= csrf_field() ?><div class="admin-grid"><label>Surname <input name="surname" value="<?= esc($b['surname'] ?? '') ?>"></label><label>First name <input name="first_name" value="<?= esc($b['first_name'] ?? '') ?>"></label><label>Other names <input name="other_names" value="<?= esc($b['other_names'] ?? '') ?>"></label><label>Gender <select name="gender"><option value="">Select</option><option value="male" <?= ($b['gender'] ?? '')==='male'?'selected':'' ?>>Male</option><option value="female" <?= ($b['gender'] ?? '')==='female'?'selected':'' ?>>Female</option><option value="other" <?= ($b['gender'] ?? '')==='other'?'selected':'' ?>>Other</option></select></label><label>Date of birth <input type="date" name="date_of_birth" value="<?= esc($b['date_of_birth'] ?? '') ?>"></label><label>Phone <input name="phone_e164" value="<?= esc($b['phone_e164'] ?? '') ?>" inputmode="tel"></label><label>Email <input name="email" value="<?= esc($b['email'] ?? '') ?>" inputmode="email"></label><label>State of origin <input name="state_of_origin" value="<?= esc($b['state_of_origin'] ?? '') ?>"></label><label>LGA of origin <input name="lga_of_origin" value="<?= esc($b['lga_of_origin'] ?? '') ?>"></label><label>Nationality <input name="nationality" value="<?= esc($b['nationality'] ?? 'Nigerian') ?>"></label></div><label>Residential address <textarea name="residential_address"><?= esc($b['residential_address'] ?? '') ?></textarea></label><label>Next of kin name <input name="next_of_kin_name" value="<?= esc($b['next_of_kin_name'] ?? '') ?>"></label><label>Next of kin phone <input name="next_of_kin_phone_e164" value="<?= esc($b['next_of_kin_phone_e164'] ?? '') ?>" inputmode="tel"></label><button>Save biodata draft</button><p data-autosave-message aria-live="polite"></p></form>

<section aria-labelledby="olevel-heading"><h2 id="olevel-heading">O'Level results</h2><p>Add at least one sitting. Use official WAEC, NECO, or NABTEB details where available.</p><?php foreach (($olevel['sittings'] ?? []) as $sitting): ?><article><strong><?= esc($sitting['sitting_label']) ?></strong><ul><?php foreach (($sitting['results'] ?? []) as $result): ?><li><?= esc($result['subject_name']) ?> — <?= esc($result['grade_code']) ?></li><?php endforeach ?></ul></article><?php endforeach ?><form method="post" action="<?= site_url('applicant/applications/'.$application['public_token'].'/olevel') ?>" id="applicant-olevel-form" data-csrf-header="<?= esc(csrf_header()) ?>" data-csrf-token="<?= esc(csrf_hash()) ?>"><?= csrf_field() ?><div class="admin-grid"><label>Exam type <select name="exam_type_code"><?php foreach (($olevel['references']['exam_types'] ?? []) as $exam): ?><option value="<?= esc($exam['code']) ?>"><?= esc($exam['code']) ?></option><?php endforeach ?></select></label><label>Exam year <input name="exam_year" inputmode="numeric" placeholder="2026"></label><label>Exam number <input name="exam_number"></label></div><div data-olevel-rows><div class="admin-grid"><label>Subject <select name="results[0][subject_code]"><?php foreach (($olevel['references']['subjects'] ?? []) as $subject): ?><option value="<?= esc($subject['code']) ?>"><?= esc($subject['label']) ?></option><?php endforeach ?></select></label><label>Grade <select name="results[0][grade_code]"><?php foreach (($olevel['references']['grades'] ?? []) as $grade): ?><option value="<?= esc($grade['code']) ?>"><?= esc($grade['code']) ?></option><?php endforeach ?></select></label></div></div><button type="button" data-add-olevel-row>Add another subject</button><button>Save O'Level</button></form></section>

<section aria-labelledby="documents-heading"><h2 id="documents-heading">Documents</h2><p>Upload configured admission documents only. Files remain private and are downloaded through authorization checks.</p><ul><?php foreach (($documents ?? []) as $document): ?><li><?= esc($document['document_type']) ?> — <a href="<?= site_url('applicant/documents/'.$document['public_token']) ?>"><?= esc($document['original_name']) ?></a></li><?php endforeach ?></ul><form method="post" enctype="multipart/form-data" action="<?= site_url('applicant/applications/'.$application['public_token'].'/documents') ?>"><?= csrf_field() ?><label>Document type <input name="document_type" placeholder="BIRTH_CERTIFICATE"></label><label>File <input type="file" name="document" accept="application/pdf,image/jpeg,image/png"></label><button>Upload or replace document</button></form></section>

<section aria-labelledby="readiness-heading"><h2 id="readiness-heading">Preview readiness</h2><?php if (! empty($completion['missing'])): ?><ul><?php foreach ($completion['missing'] as $missing): ?><li><?= esc($missing) ?></li><?php endforeach ?></ul><?php else: ?><p class="notice">Your application is ready for preview and submission.</p><?php endif ?><p><a class="button" href="<?= site_url('applicant/applications/'.$application['public_token'].'/preview') ?>">Preview application</a></p></section>
</div></section><script type="module" src="<?= base_url('assets/js/applicant-draft.js') ?>"></script><script type="module" src="<?= base_url('assets/js/applicant-olevel.js') ?>"></script>
<?= $this->endSection() ?>
