<?= $this->extend('layouts/tenant_admin') ?><?= $this->section('content') ?>
<h1>Review application <?= esc($application['application_number'] ?? $application['id']) ?></h1><?php if (session('message')): ?><p class="notice"><?= esc(session('message')) ?></p><?php endif ?><?php if (session('errors')): ?><ul><?php foreach(session('errors') as $error): ?><li><?= esc($error) ?></li><?php endforeach ?></ul><?php endif ?>
<section class="admin-grid"><article class="admin-card"><strong>Status</strong><br><?= esc($application['status']) ?></article><article class="admin-card"><strong>Applicant</strong><br><?= esc(($biodata['surname'] ?? '').' '.($biodata['first_name'] ?? '')) ?></article><article class="admin-card"><strong>Contact</strong><br><?= esc($biodata['email'] ?? $profile['email'] ?? '') ?><br><?= esc($biodata['phone_e164'] ?? $profile['phone_e164'] ?? '') ?></article></section>
<h2>Private application review</h2><form method="post" action="<?= site_url('tenant/admissions/applications/'.$application['id'].'/review') ?>"><?= csrf_field() ?><label>Review status <select name="review_status"><option value="in_review">In review</option><option value="correction_requested">Request correction</option><option value="reviewed">Reviewed</option><option value="screening_pending">Screening pending</option></select></label><label>Private notes <textarea name="private_notes"></textarea></label><label>Applicant correction message <textarea name="public_correction_message"></textarea></label><label>Correction hours <input name="correction_hours" inputmode="numeric" value="72"></label><button>Save review</button></form>
<h2>Documents</h2><?php foreach($documents as $document): ?><article class="admin-card"><strong><?= esc($document['document_type']) ?></strong> — <?= esc($document['review_status']) ?><br><a href="<?= site_url('applicant/documents/'.$document['public_token']) ?>">Download private file</a><form method="post" action="<?= site_url('tenant/admissions/documents/'.$document['id'].'/review') ?>"><?= csrf_field() ?><label>Decision <select name="decision"><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="needs_correction">Needs correction</option></select></label><label>Private note <textarea name="private_notes"></textarea></label><label>Applicant message <textarea name="applicant_message"></textarea></label><button>Save document review</button></form></article><?php endforeach ?>
<h2>O'Level</h2><?php foreach($olevelSittings as $sitting): ?><article><strong><?= esc($sitting['sitting_label']) ?></strong><ul><?php foreach($sitting['results'] as $result): ?><li><?= esc($result['subject_name']) ?> — <?= esc($result['grade_code']) ?></li><?php endforeach ?></ul></article><?php endforeach ?>
<h2>Screening</h2><form method="post" action="<?= site_url('tenant/admissions/applications/'.$application['id'].'/screening') ?>"><?= csrf_field() ?><label>Type <input name="screening_type" value="manual_review"></label><label>Scheduled at <input type="datetime-local" name="scheduled_at"></label><label>Held at <input type="datetime-local" name="held_at"></label><label>Venue <input name="venue"></label><label>Score <input name="score" inputmode="decimal"></label><label>Outcome <select name="outcome"><option value="pending">Pending</option><option value="passed">Passed</option><option value="failed">Failed</option><option value="absent">Absent</option><option value="referred">Referred</option></select></label><label>Private notes <textarea name="private_notes"></textarea></label><button>Save screening</button></form>

<h2>Phase 5 decision</h2><form method="post" action="<?= site_url('tenant/admissions/decisions/applications/'.$application['id']) ?>"><?= csrf_field() ?><label>Decision <select name="decision_type"><option value="shortlisted">Shortlist</option><option value="waitlisted">Waitlist</option><option value="rejected">Reject</option><option value="offered">Offer admission</option></select></label><input type="hidden" name="requires_approval" value="0"><label><input type="checkbox" name="requires_approval" value="1"> Require approval before offer issuance</label><label>Offer valid days <input name="offer_valid_days" inputmode="numeric" value="14"></label><label>Offer letter template key <input name="offer_letter_template_key" value="default"></label><label>Decision reason <textarea name="decision_reason"></textarea></label><label>Private notes <textarea name="private_notes"></textarea></label><button>Save decision</button></form>
<h2>Existing reviews</h2><ul><?php foreach($reviews as $review): ?><li><?= esc($review['review_status']) ?> — <?= esc($review['reviewed_at'] ?? '') ?><?php if(! empty($review['private_notes'])): ?> (private note recorded)<?php endif ?></li><?php endforeach ?></ul>
<h2>Audit foundation</h2><?php if ($auditEvents === []): ?><p>No visible audit events or missing audit-view authority.</p><?php else: ?><ul><?php foreach($auditEvents as $event): ?><li><?= esc($event['created_at']) ?> — <?= esc($event['action']) ?> — <?= esc($event['summary'] ?? '') ?></li><?php endforeach ?></ul><?php endif ?>
<?= $this->endSection() ?>
