<?= $this->extend('layouts/tenant_admin') ?><?= $this->section('content') ?><header class="page-head"><p class="eyebrow">Institution setup</p><h1>School configuration</h1><p>Maintain the academic structure used by website and admissions workflows.</p></header><?= $this->include('tenant/admin/_messages') ?>
<div class="admin-grid">
<section class="panel"><h2>Institution profile</h2><form method="post" action="<?= site_url('tenant/admin/configuration/profile') ?>"><?= csrf_field() ?><?php foreach (['institution_name'=>'Institution name','short_name'=>'Short name','official_email'=>'Official email','official_phone'=>'Official phone','address'=>'Address','state'=>'State','lga'=>'LGA'] as $name=>$label): ?><label><?= $label ?><input <?= $name==='official_email'?'type="email"':'' ?> name="<?= $name ?>" value="<?= esc(old($name, $profile[$name] ?? '')) ?>" <?= $name==='institution_name'?'required':'' ?>></label><?php endforeach ?><button>Save profile</button></form></section>
<section class="panel"><h2>Academic sessions</h2><form method="post" action="<?= site_url('tenant/admin/configuration/sessions') ?>"><?= csrf_field() ?><label>Name<input name="name" placeholder="2026/2027" required></label><div class="form-row"><label>Starts<input type="date" name="start_date"></label><label>Ends<input type="date" name="end_date"></label></div><label class="check"><input type="checkbox" name="is_current" value="1"> Current session</label><button>Add session</button></form><?= view('tenant/admin/_records',['records'=>$sessions,'primary'=>'name']) ?></section>
<section class="panel"><h2>Semesters</h2><form method="post" action="<?= site_url('tenant/admin/configuration/semesters') ?>"><?= csrf_field() ?><label>Name<input name="name" required></label><label>Code<input name="code"></label><button>Add semester</button></form><?= view('tenant/admin/_records',['records'=>$semesters,'primary'=>'name']) ?></section>
<section class="panel"><h2>Levels / years</h2><form method="post" action="<?= site_url('tenant/admin/configuration/levels') ?>"><?= csrf_field() ?><label>Name<input name="name" required></label><label>Code<input name="code"></label><label>Order<input type="number" name="sort_order" value="0"></label><button>Add level</button></form><?= view('tenant/admin/_records',['records'=>$levels,'primary'=>'name']) ?></section>
<section class="panel"><h2>Departments</h2><form method="post" action="<?= site_url('tenant/admin/configuration/departments') ?>"><?= csrf_field() ?><label>Name<input name="name" required></label><label>Code<input name="code"></label><label>Color<input type="color" name="color_hex" value="#0f766e"></label><button>Add department</button></form><?= view('tenant/admin/_records',['records'=>$departments,'primary'=>'name']) ?></section>
<section class="panel"><h2>Programmes</h2><form method="post" action="<?= site_url('tenant/admin/configuration/programmes') ?>"><?= csrf_field() ?><label>Department<select name="department_id" required><option value="">Select department</option><?php foreach($departments as $row):?><option value="<?= $row['id'] ?>"><?= esc($row['name']) ?></option><?php endforeach ?></select></label><label>Name<input name="name" required></label><label>Code<input name="code"></label><label>Duration (years)<input type="number" min="1" name="duration_years"></label><button>Add programme</button></form><?= view('tenant/admin/_records',['records'=>$programmes,'primary'=>'name']) ?></section>
<section class="panel"><h2>Courses</h2><form method="post" action="<?= site_url('tenant/admin/configuration/courses') ?>"><?= csrf_field() ?><label>Department<select name="department_id"><option value="">Institution-wide</option><?php foreach($departments as $row):?><option value="<?= $row['id'] ?>"><?= esc($row['name']) ?></option><?php endforeach ?></select></label><label>Course title<input name="title" required></label><label>Course code<input name="course_code" required></label><label>Credit units<input type="number" min="0" name="credit_units" value="0"></label><button>Add course</button></form><?= view('tenant/admin/_records',['records'=>$courses,'primary'=>'course_code','secondary'=>'title']) ?></section>
<section class="panel"><h2>Programme-course mapping</h2><form method="post" action="<?= site_url('tenant/admin/configuration/programme-courses') ?>"><?= csrf_field() ?><label>Programme<select name="programme_id" required><?php foreach($programmes as $row):?><option value="<?= $row['id'] ?>"><?= esc($row['name']) ?></option><?php endforeach ?></select></label><label>Course<select name="course_id" required><?php foreach($courses as $row):?><option value="<?= $row['id'] ?>"><?= esc($row['course_code'].' — '.$row['title']) ?></option><?php endforeach ?></select></label><label>Level<select name="level_id"><option value="">Any</option><?php foreach($levels as $row):?><option value="<?= $row['id'] ?>"><?= esc($row['name']) ?></option><?php endforeach ?></select></label><label>Semester<select name="semester_id"><option value="">Any</option><?php foreach($semesters as $row):?><option value="<?= $row['id'] ?>"><?= esc($row['name']) ?></option><?php endforeach ?></select></label><label class="check"><input type="checkbox" name="is_required" value="1" checked> Required course</label><button>Map course</button></form><p class="muted"><?= count($mappings) ?> mapping(s)</p></section>
</div><?= $this->endSection() ?>
