<?= $this->extend('layouts/platform_admin') ?>
<?= $this->section('content') ?>
<p><a href="<?= site_url('platform/tenants') ?>">← All schools</a></p>
<header class="page-head"><div><p class="eyebrow">Tenant operations</p><h1><?= esc($tenant['school_name']) ?></h1><p><span class="badge badge-<?= esc($tenant['status']) ?>"><?= esc(str_replace('_', ' ', $tenant['status'])) ?></span></p></div></header>
<?= $this->include('platform/_messages') ?>
<div class="admin-grid">
<section class="panel"><h2>Institution record</h2><form method="post" action="<?= site_url('platform/tenants/' . $tenant['id']) ?>"><?= csrf_field() ?>
<label>School name<input name="school_name" value="<?= esc($tenant['school_name']) ?>" required></label><label>Short name<input name="short_name" value="<?= esc($tenant['short_name'] ?? '') ?>"></label><label>Slug<input name="slug" value="<?= esc($tenant['slug']) ?>" required></label><label>Official email<input type="email" name="official_email" value="<?= esc($tenant['official_email'] ?? '') ?>"></label><label>Official phone<input name="official_phone" value="<?= esc($tenant['official_phone'] ?? '') ?>"></label><button>Save institution</button></form></section>
<section class="panel"><h2>Lifecycle</h2><p>Current status: <strong><?= esc(str_replace('_',' ',$tenant['status'])) ?></strong>. Changes require an operational reason and are fully audited.</p><?php if($allowedTransitions===[]):?><div class="empty">This lifecycle state is terminal.</div><?php else:?><form method="post" action="<?= site_url('platform/tenants/' . $tenant['id'] . '/lifecycle') ?>"><?= csrf_field() ?><label>New status<select name="status" required><?php foreach ($allowedTransitions as $status): ?><option value="<?= $status ?>"><?= esc(ucwords(str_replace('_',' ',$status))) ?></option><?php endforeach ?></select></label><label>Reason<textarea name="reason" minlength="10" required></textarea></label><button>Apply lifecycle change</button></form><?php endif?></section>
<section class="panel"><h2>Domains</h2><form method="post" action="<?= site_url('platform/tenants/' . $tenant['id'] . '/domains') ?>"><?= csrf_field() ?><label>Hostname<input name="domain" placeholder="school.example.edu" required></label><label>Type<select name="type"><option value="subdomain">Platform subdomain</option><option value="custom_domain">Custom domain</option></select></label><label class="check"><input type="checkbox" name="is_primary" value="1"> Primary hostname</label><button>Save hostname</button></form><ul class="record-list"><?php foreach ($domains as $domain): ?><li><strong><?= esc($domain['domain']) ?></strong> <span class="badge"><?= esc($domain['type']) ?></span><?= $domain['is_primary'] ? ' · Primary' : '' ?></li><?php endforeach ?></ul></section>
<section class="panel"><h2>Platform audit</h2><?php if ($audit === []): ?><div class="empty">No platform events for this school.</div><?php else: ?><ul class="record-list"><?php foreach ($audit as $event): ?><li><strong><?= esc($event['action']) ?></strong><br><?= esc($event['summary'] ?? '') ?><br><small><?= esc($event['created_at']) ?></small></li><?php endforeach ?></ul><?php endif ?></section>
</div>
<?= $this->endSection() ?>
